export const Internation = {
  'zh-CN': {
    basic: '基本用法',
    chooseCity: '请选择城市',
    defaultSelected: '默认选中项',
    tileDesc: '平铺展示',
    multipleColumns: '多列样式',
    chooseTime: '请选择时间',
    cascade: '多级联动',
    async: '异步获取',
    custom: '自定义按钮',
    validTime: '请选择有效日期',
    chooseDate: '选择日期',
    always: '永远有效',
    monday: '周一',
    tuesday: '周二',
    wednesday: '周三',
    thursday: '周四',
    friday: '周五',
    morning: '上午',
    afternoon: '下午',
    evening: '晚上',
    nanJing: '南京市',
    wuXi: '无锡市',
    zangZu: '海北藏族自治区',
    beiJing: '北京市',
    lianYunGang: '连云港市',
    zheJiang: '浙江市',
    jiangSu: '江苏市',
    hangZhou: '杭州',
    xiHu: '西湖区',
    yuHang: '余杭区',
    wenZhou: '温州',
    luCheng: '鹿城区',
    ouHai: '瓯海区',
    fuJian: '福建',
    fuZhou: '福州',
    xiaMen: '厦门',
    guLou: '鼓楼区',
    taiJiang: '台江区',
    siMing: '思明区',
    haiCang: '海沧区'
  },
  'en-US': {
    basic: 'Basic Usage',
    chooseCity: 'Choose City',
    defaultSelected: 'Default Index',
    tileDesc: 'Tile',
    multipleColumns: 'Multiple Columns',
    chooseTime: 'Choose Time',
    cascade: 'Cascade',
    async: 'Async',
    custom: 'Slots',
    validTime: 'Valid Time',
    chooseDate: 'Choose Date',
    always: 'Always',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    nanJing: 'NanJing',
    wuXi: 'WuXi',
    zangZu: 'ZangZu',
    beiJing: 'BeiJing',
    lianYunGang: 'LianYunGang',
    zheJiang: 'ZheJiang',
    jiangSu: 'JiangSu',
    hangZhou: 'HangZhou',
    xiHu: 'XiHu',
    yuHang: 'YuHang',
    wenZhou: 'WenZhou',
    luCheng: 'LuCheng',
    ouHai: 'OuHai',
    fuJian: 'FuJian',
    fuZhou: 'FuZhou',
    xiaMen: 'XiaMen',
    guLou: 'GuLou',
    taiJiang: 'TaiJiang',
    siMing: 'SiMing',
    haiCang: 'HaiCang'
  }
};
