const address = {
    'province':[{"cod":false,"id":1,"name":"北京"},{"cod":false,"id":20,"name":"广西"},{"cod":false,"id":21,"name":"江西"},{"cod":false,"id":22,"name":"四川"},{"cod":false,"id":23,"name":"海南"},{"cod":false,"id":24,"name":"贵州"},{"cod":false,"id":25,"name":"云南"},{"cod":false,"id":26,"name":"西藏"},{"cod":false,"id":27,"name":"陕西"},{"cod":false,"id":28,"name":"甘肃"},{"cod":false,"id":29,"name":"青海"},{"cod":false,"id":30,"name":"宁夏"},{"cod":false,"id":31,"name":"新疆"},{"cod":false,"id":32,"name":"台湾"},{"cod":false,"id":84,"name":"钓鱼岛"},{"cod":false,"id":19,"name":"广东"},{"cod":false,"id":18,"name":"湖南"},{"cod":false,"id":2,"name":"上海"},{"cod":false,"id":3,"name":"天津"},{"cod":false,"id":4,"name":"重庆"},{"cod":false,"id":5,"name":"河北"},{"cod":false,"id":6,"name":"山西"},{"cod":false,"id":7,"name":"河南"},{"cod":false,"id":8,"name":"辽宁"},{"cod":false,"id":9,"name":"吉林"},{"cod":false,"id":10,"name":"黑龙江"},{"cod":false,"id":17,"name":"湖北"},{"cod":false,"id":16,"name":"福建"},{"cod":false,"id":15,"name":"浙江"},{"cod":false,"id":14,"name":"安徽"},{"cod":false,"id":13,"name":"山东"},{"cod":false,"id":12,"name":"江苏"},{"cod":false,"id":11,"name":"内蒙古"},{"cod":false,"id":52993,"name":"港澳"}],
    'city':[{"cod":false,"id":72,"name":"朝阳区"},{"cod":false,"id":2803,"name":"崇文区"},{"cod":false,"id":2901,"name":"昌平区"},{"cod":false,"id":2806,"name":"石景山区"},{"cod":false,"id":2810,"name":"大兴区"},{"cod":false,"id":2802,"name":"东城区"},{"cod":false,"id":2808,"name":"房山区"},{"cod":false,"id":2805,"name":"丰台区"},{"cod":false,"id":2814,"name":"怀柔区"},{"cod":false,"id":2800,"name":"海淀区"},{"cod":false,"id":2807,"name":"门头沟"},{"cod":false,"id":2816,"name":"密云区"},{"cod":false,"id":2953,"name":"平谷区"},{"cod":false,"id":2812,"name":"顺义区"},{"cod":false,"id":2809,"name":"通州区"},{"cod":false,"id":2804,"name":"宣武区"},{"cod":false,"id":2801,"name":"西城区"},{"cod":false,"id":3065,"name":"延庆区"}],
    'country':[{"cod":false,"id":55653,"name":"八里庄街道"},{"cod":false,"id":4139,"name":"北苑"},{"cod":false,"id":55654,"name":"常营乡"},{"cod":false,"id":55655,"name":"朝外街道"},{"cod":false,"id":55656,"name":"崔各庄乡"},{"cod":false,"id":55657,"name":"大屯街道"},{"cod":false,"id":4211,"name":"定福庄"},{"cod":false,"id":55661,"name":"豆各庄乡"},{"cod":false,"id":55658,"name":"东坝乡"},{"cod":false,"id":55659,"name":"东风乡"},{"cod":false,"id":55660,"name":"东湖街道"},{"cod":false,"id":55662,"name":"垡头街道"},{"cod":false,"id":4137,"name":"管庄地区"},{"cod":false,"id":55663,"name":"高碑店乡"},{"cod":false,"id":55664,"name":"和平街街道"},{"cod":false,"id":55665,"name":"黑庄户乡"},{"cod":false,"id":55666,"name":"呼家楼街道"},{"cod":false,"id":55667,"name":"建外街道"},{"cod":false,"id":55668,"name":"将台乡"},{"cod":false,"id":55671,"name":"酒仙桥街道"},{"cod":false,"id":55670,"name":"劲松街道"},{"cod":false,"id":55669,"name":"金盏乡"},{"cod":false,"id":55673,"name":"六里屯街道"},{"cod":false,"id":55672,"name":"来广营乡"},{"cod":false,"id":55674,"name":"麦子店街道"},{"cod":false,"id":55675,"name":"南磨房乡"},{"cod":false,"id":55677,"name":"平房乡"},{"cod":false,"id":55676,"name":"潘家园街道"},{"cod":false,"id":55682,"name":"双井街道"},{"cod":false,"id":55680,"name":"十八里店乡"},{"cod":false,"id":55681,"name":"首都机场街道"},{"cod":false,"id":2839,"name":"四环到五环之间"},{"cod":false,"id":2819,"name":"三环到四环之间"},{"cod":false,"id":2799,"name":"三环以内"},{"cod":false,"id":55678,"name":"三间房乡"},{"cod":false,"id":55679,"name":"三里屯街道"},{"cod":false,"id":55683,"name":"孙河乡"},{"cod":false,"id":55685,"name":"团结湖街道"},{"cod":false,"id":55684,"name":"太阳宫乡"},{"cod":false,"id":55687,"name":"望京街道"},{"cod":false,"id":55686,"name":"王四营乡"},{"cod":false,"id":2840,"name":"五环到六环之间"},{"cod":false,"id":55688,"name":"香河园街道"},{"cod":false,"id":55689,"name":"小关街道"},{"cod":false,"id":55690,"name":"小红门乡"},{"cod":false,"id":55691,"name":"亚运村街道"},{"cod":false,"id":55692,"name":"左家庄街道"},{"cod":false,"id":55652,"name":"奥运村街道"},{"cod":false,"id":55651,"name":"安贞街道"}],
    'town':[],
    'addressList':[
        {"id":1,"addressDetail":"th ","cityName":"石景山区","countyName":"城区","provinceName":"北京","selectedAddress":true,"townName":""},
        {"id":2,"addressDetail":"12_ ","cityName":"电饭锅","countyName":"扶绥县","provinceName":"北京","selectedAddress":false,"townName":""},
        {"id":3,"addressDetail":"发大水比 ","cityName":"放到","countyName":"广宁街道","provinceName":"钓鱼岛全区","selectedAddress":false,"townName":""},
        {"id":4,"addressDetail":"还是想吧百度吧 ","cityName":"研发","countyName":"八里庄街道","provinceName":"北京","selectedAddress":false,"townName":""},
    ]
}
export default address