module.exports = {
  name: 'nutui-icon',
  // 功能图标小尺寸
  sizeSmall: [
    'ask',
    'tips',
    'notice',
    'lower',
    'top',
    'download',
    'dongdong',
    'JIMI40',
    'location',
    'scan',
    'addfollow',
    'search',
    'share',
    'follow',
    'del',
    'edit',
    'cart',
    'home',
    'find',
    'category',
    'my',
    'footprint',
    'link',
    'scan2',
    'left',
    'close',
    'locationg3',
    'share',
    'shop3',
    'message',
    'ask2',
    'search2',
    'clock',
    'setting',
    'refresh2',
    'horizontal',
    'date',
    'photograph',
    'more-s'
  ],
  // 规范里面的粗icon
  sizeBold: [
    'order',
    'refresh',
    'add',
    'JD',
    'eye',
    'dshop',
    'my2',
    'star',
    'del2',
    'more-x',
    'comment',
    'microphone',
    'people',
    'service',
    'cart2',
    'location2',
    'marshalling',
    'fabulous',
    's-follow',
    'shop',
    'jdl'
  ],
  // 基础图标
  basic: [
    'uplode',
    'mask-close',
    'circle-close',
    'right',
    'arrow-right',
    'github',
    'screen-little',
    'plus',
    'minus',
    'Check',
    'issue',
    'failure',
    'success',
    'retweet',
    'poweroff-circle-fill',
    'play-circle-fill',
    'checked',
    'checklist',
    'check-disabled',
    'check-normal',
    'check-checked',
    'loading'
  ],

  // 应用图标
  app: [
    'arrow-up',
    'arrow-down',
    'arrow-up2',
    'arrow-down2',
    'down-arrow',
    'joy-smile',
    'close-little',
    'horizontal-nv',
    'share-n',
    'nut-icon-heart1',
    'nut-icon-heart-fill',
    'nut-icon-star-n',
    'nut-icon-star-fill-n'
  ]
};
