export type AnimateType =
  | 'shake'
  | 'ripple'
  | 'breath'
  | 'float'
  | 'slide-right'
  | 'slide-left'
  | 'slide-top'
  | 'slide-bottom'
  | 'jump'
  | 'twinkle'
  | 'flicker'
export type AnimateAction = 'initial' | 'click' | ''
